name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: buildx build --platform linux/amd64,linux/arm64 . --file Dockerfile --tag wwahyudi/powerstripmonitoring-p304m:$(date +%s)
